name: cappuccino
description: "CAppuccino, coffee recepies"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.1
  lorem_ipsum: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
   - assets\images\Logo.png
   - assets\images\Cappuccino.png
   - assets\images\Flat_White.png
   - assets\images\Latte.png
   - assets\images\Macchiato.png
   - assets\images\Mocha.png

  fonts: 
   - family: Lucida
     fonts: 
      - asset: assets\fonts\LucidaHandwritingStdRg.TTF

   - family: Sitka
     fonts:
      - asset: assets\fonts\Sitka.ttc

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png

  android_12: